[versions]
h2 = "2.+"
sqlite-jdbc = "3.+"
javafx-plugin = "0.1.0"
javafx = "22.0.2"
junit = "4.+"
mockk = "1.+"

[libraries]
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
junit = { module = "junit:junit", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
javafx = { id = "org.openjfx.javafxplugin", version.ref = "javafx-plugin" }
