[versions]
versions-plugin = "0.51.0"
kotlin = "2.1.0"
h2 = "2.3.232"
sqlite-jdbc = "3.47.2.0"
javafx-plugin = "0.1.0"
javafx = "22.0.2"
junit = "4.13.2"
mockk = "1.13.16"
ktlint-plugin = "12.1.2"
ktlint = "1.5.0"

[libraries]
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
junit = { module = "junit:junit", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
javafx = { id = "org.openjfx.javafxplugin", version.ref = "javafx-plugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
